version: '2.2'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    container_name: redis_cache

  nutrium-ws:
    image: lammn224/nutrium-ws:v1-ubuntu
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis_cache
    container_name: nutrium-ws

  nutrium-web:
    image: lammn224/nutrium-web:v1
    ports:
      - "8000:8000"
    depends_on:
      - nutrium-ws
    container_name: nutrium-web-2